### ISSUE TITLE
Multiple game accounts

### ISSUE THREAD

**Issue by TomCatonly1** [leapdroid-team/leapdroid#38]
I have 2 accounts in game "Magic rush heroes". In Leapdroid version 1.6.1.0 installed via msi I was able to play both accounts at the same time. First account on VM1 second account on VM2.
Now, after clean reinstall Leapdroid to version 1.7.0.0 via installer, I am able to play only one account not matter if it is VM1 or VM2. When I switch account in game to the second one via Google play on VM1, it is also switched on VM2 (and vice versa).
Both VM have their own disks. On both VM there is only one (and different) google play account.

**Comment by LeapdroidDev99** [comment]
Hi,
This is wired issue actually. Could you please check whether the shortcuts placed on desktop launched the same VM actually? When you right click the shortcut and select "Properties", you are able to see the command line used. There is a parameter like "-s vm1". Could you please check whether they are the same?

And could you please also try to launch using command line? You can reach Windows command console by hitting Windows + R and typing cmd. Then you use "cd C:\Program Files\Leapdroid\VM" to get to the target folder. Using "LeapdroidVM.exe -vfiber -s vm1" will launch vm1 for you, while "LeapdroidVM.exe -vfiber -s vm2" will launch vm2. Could you check if the problem is still there?

**Comment by LeapdroidDev99** [comment]
Hi,
We are able to reproduce the issue. Thanks for letting us know. We will fix it and let you know as soon as possible.

**Comment by Wonyl** [comment]
Hello,
My apologies first, my english is basic, but i'm sure it's understable :p
I've a similar problem, i did two accounts for a game with different google's account. One on leapdroid and the second on another android app player(Memu).
Both game's accounts are linked by a facebook register so i would backup my second account on Leapdroid. But i can't cause the game pre-dowload my first account information, no matter if i connect with the first and second google account, it's always the first one account which is dowloaded.
I tried to desactivate many google's services in the app setting but it's imposible to restart a game since begining.Leapdroid always backup the register account information for a game compare to Memu for example which always fully restart an app.

**Comment by LeapdroidDev99** [comment]
Hi, we've fixed the issue. We probably will release it in the middle next week. Thanks for raising the issue to us.

**Comment by Wonyl** [comment]
Wow nice jobs, was fast and that will be really helpfull :)

**Comment by Wonyl** [comment]
Hi again, i removed the old and installed the new version, but the problem isn't resolved :s

**Comment by LeapdroidDev99** [comment]
@Wonyl Sorry for that. Could you please let us know the game so that we can take a look? With @TomCatonly1 's case, the issue of multiple game account is actually caused by duplication between the two VMs. So your case probably has a different reason.

**Comment by TomCatonly1** [comment]
I can confirm, that update resolved my problem. Thank you very much. You are great.
